In [13]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

x=pd.read_csv('train.csv')
xtest = pd.read_csv('test.csv')

In [14]:
def clean_cabin(x):
    try:
        return x[0]
    except TypeError:
        return "U"
    
x['Cabin'] = x.Cabin.apply(clean_cabin)

x.loc[(x['Pclass'] == 1) & (x['Cabin'] == 'U'), 'Cabin'] = 'C'
x.loc[(x['Pclass'] == 2) & (x['Cabin'] == 'U'), 'Cabin'] = 'E'
x.loc[(x['Pclass'] == 3) & (x['Cabin'] == 'U') & (x['Sex'] == 'male') , 'Cabin'] = 'F'
x.loc[(x['Pclass'] == 3) & (x['Cabin'] == 'U') & (x['Sex'] == 'female'),'Cabin'] = 'G'


def clean_cabin(x):
    try:
        return x[0]
    except TypeError:
        return "U"
    
xtest['Cabin'] = xtest.Cabin.apply(clean_cabin)

xtest.loc[(xtest['Pclass'] == 1) & (xtest['Cabin'] == 'U'), 'Cabin'] = 'C'
xtest.loc[(xtest['Pclass'] == 2) & (xtest['Cabin'] == 'U'), 'Cabin'] = 'E'
xtest.loc[(xtest['Pclass'] == 3) & (xtest['Cabin'] == 'U') & (xtest['Sex'] == 'male') , 'Cabin'] = 'F'
xtest.loc[(xtest['Pclass'] == 3) & (xtest['Cabin'] == 'U') & (xtest['Sex'] == 'female'),'Cabin'] = 'G'


dummies = pd.get_dummies(x['Cabin'], prefix = 'Deck')
x= pd.concat([x,dummies],axis =1)

x.drop (['Deck_T'],axis =1 ,inplace= True)

dummies = pd.get_dummies(xtest['Cabin'], prefix = 'Deck')
xtest= pd.concat([xtest,dummies],axis =1)

In [15]:
def title(name):
    temp_1 = name.split(',') # Split by (,)
    temp_2 = temp_1[1].split('.')[0] # Split by (.)
    temp_3 = temp_2.strip() # Remove white space
    return temp_3

x['Title'] = x['Name'].apply(title)

x ['Temp'] =x['Sex'] + x['Title'] #just for female doctors
x.loc[x['Temp'] == 'femaleDr', 'Title'] = 'Mrs' #just for female doctors

x.drop ([ 'Temp' ],axis =1 ,inplace= True) #just for female doctors

def new_title(title):
    if title == 'Mr' or title == 'Capt' or title == 'Don' or title == 'Dr' or title == 'Jonkheer' or title     == 'Major' or  title == 'Rev' or title == 'Sir' or title == 'Col':
        return 'Mr'
    elif title == 'Mrs' or title == 'Lady' or title == 'Mme' or title == 'Ms' or title == 'the       Countess':
        return 'Mrs'
    elif title == 'Miss' or title == 'Mlle':
        return 'Miss'
    else:
        return 'Master'
    
x['Title'] = x['Title'].apply(new_title)

#Creating new family_size and family column
x['Family_Size']=x['SibSp']+x['Parch']

#imputing nan values of Fare based on Class
x.loc[(x.Fare.isnull())&(x.Pclass==1),'Fare'] =np.median(x[x['Pclass'] == 1]['Fare'].dropna())
x.loc[(x.Fare.isnull())&(x.Pclass==2),'Fare'] =np.median(x[x['Pclass'] == 2]['Fare'].dropna())
x.loc[(x.Fare.isnull())&(x.Pclass==3),'Fare'] =np.median(x[x['Pclass'] == 3]['Fare'].dropna())


#instead of male and female separate columns 
#    creating a single column based on gender
x['Gender'] = x['Sex'].map( {'female': 0, 'male': 1} ).astype(int)

x.Embarked[ x.Embarked.isnull() ] = x.Embarked.dropna().mode().values

#imputing missing values of age based on salutations (Mr. ,Mrs Etc etc)
mean_ages = np.zeros(4)
mean_ages[0]=np.average(x[x['Title'] == 'Miss']['Age'].dropna())
mean_ages[1]=np.average(x[x['Title'] == 'Mrs']['Age'].dropna())
mean_ages[2]=np.average(x[x['Title'] == 'Mr']['Age'].dropna())
mean_ages[3]=np.average(x[x['Title'] == 'Master']['Age'].dropna())
x.loc[(x.Age.isnull()) & (x.Title == 'Miss') ,'Age'] = mean_ages[0]
x.loc[(x.Age.isnull()) & (x.Title == 'Mrs') ,'Age'] = mean_ages[1]
x.loc[(x.Age.isnull()) & (x.Title == 'Mr') ,'Age'] = mean_ages[2]
x.loc[(x.Age.isnull()) & (x.Title == 'Master') ,'Age'] = mean_ages[3]

#Creating category based on Age
x.loc[(x.Age<=12) ,'AgeCat'] = 'Child'
x.loc[(x.Age>49),'AgeCat'] = 'Senior'
x.loc[(x.Age>12) & (x.Age <=19),'AgeCat'] = 'Teen'
x.loc[(x.Age>19) & (x.Age <=49) ,'AgeCat'] = 'Adult'

x['AgeClass']=x ['Age']*x['Pclass']

x.loc[(x.Family_Size < 1) ,'Fam'] = 'No' 
x.loc[(x.Family_Size >0) & (x.Family_Size <3) ,'Fam'] = 'Small' 
x.loc[(x.Family_Size >2),'Fam'] = 'Large'                   
                         
#dropping column names that are not needed
x.drop (['Cabin','Name','SibSp','Parch','Ticket' ,'Sex'],axis =1 ,inplace= True)
x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 19 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Age            891 non-null float64
Fare           891 non-null float64
Embarked       891 non-null object
Deck_A         891 non-null float64
Deck_B         891 non-null float64
Deck_C         891 non-null float64
Deck_D         891 non-null float64
Deck_E         891 non-null float64
Deck_F         891 non-null float64
Deck_G         891 non-null float64
Title          891 non-null object
Family_Size    891 non-null int64
Gender         891 non-null int32
AgeCat         891 non-null object
AgeClass       891 non-null float64
Fam            891 non-null object
dtypes: float64(10), int32(1), int64(4), object(4)
memory usage: 135.7+ KB

C:\Users\admin\Anaconda\lib\site-packages\IPython\kernel\__main__.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [16]:
x.tail()

,PassengerId,Survived,Pclass,Age,Fare,Embarked,Deck_A,Deck_B,Deck_C,Deck_D,Deck_E,Deck_F,Deck_G,Title,Family_Size,Gender,AgeCat,AgeClass,Fam
886,887,0,2,27.000000,13.00,S,0,0,0,0,1,0,0,Mr,0,1,Adult,54.000000,No
887,888,1,1,19.000000,30.00,S,0,1,0,0,0,0,0,Miss,0,0,Teen,19.000000,No
888,889,0,3,21.804054,23.45,S,0,0,0,0,0,0,1,Miss,3,0,Adult,65.412162,Large
889,890,1,1,26.000000,30.00,C,0,0,1,0,0,0,0,Mr,0,1,Adult,26.000000,No
890,891,0,3,32.000000,7.75,Q,0,0,0,0,0,1,0,Mr,0,1,Adult,96.000000,No

In [17]:
# Feature transformation without creating more features
x['Embarked'] = x['Embarked'].map({'C':1, 'S':2, 'Q':3}).astype(int) 
x['Title'] = x['Title'].map({'Mr':1, 'Mrs':2, 'Master':3, 'Miss':4}).astype(int)
x['AgeCat'] = x['AgeCat'].map({'Child':1, 'Teen':2, 'Adult':3, 'Senior':4}).astype(int)

dummies = pd.get_dummies(x['Fam'], prefix = 'Fam')
x= pd.concat([x,dummies],axis =1)

x.drop (['Fam'],axis =1 ,inplace= True)

#Feature Normalization : fare,agefill,Fpp,ageclass,classfare
scaler = preprocessing.MinMaxScaler()


x['Age'] = scaler.fit_transform(x['Age'])
x['Fare'] = scaler.fit_transform(x['Fare'])
x['AgeClass'] = scaler.fit_transform(x['AgeClass'])

In [19]:
x.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 21 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Age            891 non-null float64
Fare           891 non-null float64
Embarked       891 non-null int32
Deck_A         891 non-null float64
Deck_B         891 non-null float64
Deck_C         891 non-null float64
Deck_D         891 non-null float64
Deck_E         891 non-null float64
Deck_F         891 non-null float64
Deck_G         891 non-null float64
Title          891 non-null int32
Family_Size    891 non-null int64
Gender         891 non-null int32
AgeCat         891 non-null int32
AgeClass       891 non-null float64
Fam_Large      891 non-null float64
Fam_No         891 non-null float64
Fam_Small      891 non-null float64
dtypes: float64(13), int32(4), int64(4)
memory usage: 139.2 KB

In [20]:
def title(name):
    temp_1 = name.split(',') # Split by (,)
    temp_2 = temp_1[1].split('.')[0] # Split by (.)
    temp_3 = temp_2.strip() # Remove white space
    return temp_3

xtest['Title'] = xtest['Name'].apply(title)
def new_title(title):
    if title == 'Mr' or title == 'Capt' or title == 'Don' or title == 'Dr' or title == 'Jonkheer' or title     == 'Major' or  title == 'Rev' or title == 'Sir' or title == 'Col':
        return 'Mr'
    elif title == 'Mrs' or title == 'Lady' or title == 'Mme' or title == 'Ms' or title == 'the       Countess':
        return 'Mrs'
    elif title == 'Miss' or title == 'Mlle':
        return 'Miss'
    else:
        return 'Master'
    
xtest['Title'] = xtest['Title'].apply(new_title)


#Creating new family_size and family column
xtest['Family_Size']=xtest['SibSp']+xtest['Parch']

#imputing nan values of Fare based on Class
xtest.loc[(xtest.Fare.isnull())&(xtest.Pclass==1),'Fare'] =np.median(xtest[xtest['Pclass'] == 1]['Fare'].dropna())
xtest.loc[(xtest.Fare.isnull())&(xtest.Pclass==2),'Fare'] =np.median(xtest[xtest['Pclass'] == 2]['Fare'].dropna())
xtest.loc[(xtest.Fare.isnull())&(xtest.Pclass==3),'Fare'] =np.median(xtest[xtest['Pclass'] == 3]['Fare'].dropna())

#instead of male and female separate columns 
#    creating a single column based on gender
xtest['Gender'] = xtest['Sex'].map( {'female': 0, 'male': 1} ).astype(int)

xtest.Embarked[xtest.Embarked.isnull()] = xtest.Embarked.dropna().mode().values

#imputing missing values of age based on salutations (Mr. ,Mrs Etc etc)
mean_ages = np.zeros(4)
mean_ages[0]=np.average(xtest[xtest['Title'] == 'Miss']['Age'].dropna())
mean_ages[1]=np.average(xtest[xtest['Title'] == 'Mrs']['Age'].dropna())
mean_ages[2]=np.average(xtest[xtest['Title'] == 'Mr']['Age'].dropna())
mean_ages[3]=np.average(xtest[xtest['Title'] == 'Master']['Age'].dropna())
xtest.loc[(xtest.Age.isnull()) & (xtest.Title == 'Miss') ,'Age'] = mean_ages[0]
xtest.loc[(xtest.Age.isnull()) & (xtest.Title == 'Mrs') ,'Age'] = mean_ages[1]
xtest.loc[(xtest.Age.isnull()) & (xtest.Title == 'Mr') ,'Age'] = mean_ages[2]
xtest.loc[(xtest.Age.isnull()) & (xtest.Title == 'Master') ,'Age'] = mean_ages[3]

#Based on age creating a categorical column 

xtest.loc[(xtest.Age<=12) ,'AgeCat'] = 1
xtest.loc[(xtest.Age>49),'AgeCat'] = 4
xtest.loc[(xtest.Age>12) & (xtest.Age <=19),'AgeCat'] = 2
xtest.loc[(xtest.Age>19) & (xtest.Age <=49) ,'AgeCat'] = 3


xtest['AgeClass']=xtest['Age']*xtest['Pclass']

xtest.loc[(xtest.Family_Size < 1) ,'Fam'] = 'No' 
xtest.loc[(xtest.Family_Size >0) & (xtest.Family_Size <3) ,'Fam'] = 'Small' 
xtest.loc[(xtest.Family_Size >2),'Fam'] = 'Large'                   

xtest.drop (['Cabin','Name','SibSp','Parch','Ticket' ,'Sex'],axis =1 ,inplace= True)

C:\Users\admin\Anaconda\lib\site-packages\IPython\kernel\__main__.py:33: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [ ]:
# Feature transformation without creating more features
xtest['Embarked'] = xtest['Embarked'].map({'C':1, 'S':2, 'Q':3}).astype(int) 
xtest['Title'] = xtest['Title'].map({'Mr':1, 'Mrs':2, 'Master':3, 'Miss':4}).astype(int)
#xtest['AgeCat'] = xtest['AgeCat'].map({'Child':1, 'Teen':2, 'Adult':3, 'Senior':4}).astype(int)


#Feature Normalization : fare,agefill,Fpp,ageclass,classfare
scaler_test = preprocessing.MinMaxScaler()


xtest['Age'] = scaler_test.fit_transform(xtest['Age'])
xtest['Fare'] = scaler_test.fit_transform(xtest['Fare'])
xtest['AgeClass'] = scaler_test.fit_transform(xtest['AgeClass'])